baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Link Tree'
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params]
  attribution = false

  [params.author]
    name = "Mirai Kumiko"
    headline = "My example link tree^^~"
    image = "images/avatar.jpg"
    links = [
      { link = { href = "https://example.com", text = "Website" } },
      { youtube = "https://example.com" },
      { twitch = "https://example.com" },
      { instagram = "https://example.com" },
      { telegram = "https://example.com" },
      { x = "https://example.com" },
      { linkedin = "https://example.com" },
      { mastodon = "https://example.com" },
      { bluesky = "https://example.com" },
      { patreon = "https://example.com" }
    ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
